[tool.black]
line-length = 100
target-version = ["py311"]
exclude = "\\.venv|dist|build|__pycache__|.git|.chroma|memory|logs"

[tool.ruff]
line-length = 100
target-version = "py311"
select = ["E","F","I","UP","W","B"]
ignore = ["E203","E501"]
exclude = [".venv","dist","build","__pycache__", ".git",".chroma","memory","logs"]

[tool.isort]
profile = "black"
line_length = 100
